//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korsun_PP23.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int IdTransport { get; set; }
        public int IdTransportType { get; set; }
        public string TransportName { get; set; }
        public string GOSNumber { get; set; }
        public int IdUser { get; set; }
    
        public virtual TransportType TransportType { get; set; }
        public virtual User User { get; set; }
    }
}
