//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korsun_PP23.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int IdWarehouse { get; set; }
        public int IdAddress { get; set; }
        public string WarehouseName { get; set; }
        public string WarPhoneNumber { get; set; }
        public Nullable<int> IdContract { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
